# Generated by Django 5.2.14 on 2026-05-15 00:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(choices=[('Barangay Clearance', 'Barangay Clearance'), ('Certificate of Indigency', 'Certificate of Indigency'), ('Certificate of Residency', 'Certificate of Residency')], help_text='Determines which detail table (clearance/indigency/residency) has the matching row.', max_length=40)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Ready for Pickup', 'Ready for Pickup'), ('Claimed', 'Claimed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('or_number', models.CharField(blank=True, help_text='Official Receipt number if a processing fee was collected.', max_length=50, null=True)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Maintained by PostgreSQL trigger trg_requests_updated_at.')),
            ],
            options={
                'db_table': 'certificate_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(help_text='bcrypt hash only — never store plain text.', max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Secretary', 'Secretary'), ('Encoder', 'Encoder')], default='Encoder', help_text='Admin: full access. Secretary: process + generate. Encoder: new requests only.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_data', models.TextField(help_text='The request UUID cast to text — this is what the QR image encodes.')),
                ('image_path', models.CharField(blank=True, help_text='File path or URL to the PNG. NULL until the image has been saved.', max_length=500, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='api.certificaterequest')),
            ],
            options={
                'db_table': 'qr_codes',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('age', models.SmallIntegerField(help_text='Snapshot age at time of registration; should correspond to date_of_birth.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(129)])),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Legally Separated', 'Legally Separated')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(default='Filipino', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Maintained by PostgreSQL trigger trg_residents_updated_at.')),
            ],
            options={
                'db_table': 'residents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='idx_residents_full_name')],
            },
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificate_requests', to='api.resident'),
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(choices=[('Barangay Clearance', 'Barangay Clearance'), ('Certificate of Indigency', 'Certificate of Indigency'), ('Certificate of Residency', 'Certificate of Residency')], max_length=40)),
                ('cert_content', models.TextField(help_text='Full rendered certificate text/HTML ready for printing.')),
                ('is_printed', models.BooleanField(default=False, help_text='Set to TRUE when staff confirms the physical certificate was printed.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='generated_certificate', to='api.certificaterequest')),
                ('generated_by', models.ForeignKey(db_column='generated_by', on_delete=django.db.models.deletion.RESTRICT, related_name='generated_certificates', to='api.staff')),
            ],
            options={
                'db_table': 'generated_certificates',
            },
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='encoded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='encoded_requests', to='api.staff'),
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Ready for Pickup', 'Ready for Pickup'), ('Claimed', 'Claimed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], help_text='NULL when this is the initial creation entry for a new request.', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Ready for Pickup', 'Ready for Pickup'), ('Claimed', 'Claimed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(db_column='changed_by', on_delete=django.db.models.deletion.RESTRICT, related_name='status_changes', to='api.staff')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.certificaterequest')),
            ],
            options={
                'db_table': 'status_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('pickup_time_slot', models.CharField(help_text="e.g. '9:00 AM – 10:00 AM'.", max_length=30)),
                ('pickup_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('No Show', 'No Show'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Maintained by PostgreSQL trigger trg_appointments_updated_at.')),
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='api.certificaterequest')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['pickup_date'],
                'indexes': [models.Index(fields=['pickup_date'], name='idx_appointments_pickup_date')],
            },
        ),
        migrations.CreateModel(
            name='ClearanceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('id_type_presented', models.CharField(help_text="e.g. 'PhilSys ID', 'Voter's ID', 'Passport'.", max_length=80)),
                ('id_number', models.CharField(blank=True, help_text='ID number (optional if staff records visually).', max_length=80, null=True)),
                ('with_community_tax', models.BooleanField(default=False, help_text='TRUE if the resident presented a Community Tax Certificate (Cedula).')),
                ('ctc_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ctc_date_issued', models.DateField(blank=True, null=True)),
                ('ctc_place_issued', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='clearance_detail', to='api.certificaterequest')),
            ],
            options={
                'db_table': 'clearance_details',
                'indexes': [models.Index(fields=['request'], name='idx_clearance_request_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('with_community_tax', False), models.Q(('ctc_number__isnull', False), ('ctc_date_issued__isnull', False), ('ctc_place_issued__isnull', False)), _connector='OR'), name='chk_ctc_complete')],
            },
        ),
        migrations.CreateModel(
            name='IndigencyDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('monthly_income', models.CharField(default='Below minimum wage', help_text="Descriptive income range (e.g. 'Below minimum wage'). Not an exact figure.", max_length=50)),
                ('num_dependents', models.SmallIntegerField(default=0, help_text='Number of dependents in the household.', validators=[django.core.validators.MinValueValidator(0)])),
                ('for_medical', models.BooleanField(default=False)),
                ('for_scholarship', models.BooleanField(default=False)),
                ('for_burial', models.BooleanField(default=False)),
                ('for_legal_aid', models.BooleanField(default=False)),
                ('for_government_aid', models.BooleanField(default=False, help_text='DSWD, 4Ps, etc.')),
                ('for_other', models.BooleanField(default=False)),
                ('other_purpose_details', models.TextField(blank=True, help_text='Required when for_other = TRUE.', null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=150, null=True)),
                ('beneficiary_relation', models.CharField(blank=True, help_text="e.g. 'Self', 'Daughter', 'Son'.", max_length=80, null=True)),
                ('requesting_institution', models.CharField(blank=True, help_text="e.g. 'Cebu City Medical Center', 'UST'.", max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='indigency_detail', to='api.certificaterequest')),
            ],
            options={
                'db_table': 'indigency_details',
                'indexes': [models.Index(fields=['request'], name='idx_indigency_request_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('for_other', False), ('other_purpose_details__isnull', False), _connector='OR'), name='chk_other_purpose'), models.CheckConstraint(condition=models.Q(('for_medical', True), ('for_scholarship', True), ('for_burial', True), ('for_legal_aid', True), ('for_government_aid', True), ('for_other', True), _connector='OR'), name='chk_at_least_one_purpose')],
            },
        ),
        migrations.CreateModel(
            name='ResidencyDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('years_of_residency', models.SmallIntegerField(default=0, help_text='Full years the resident has lived in Brgy. Zapatera.', validators=[django.core.validators.MinValueValidator(0)])),
                ('months_of_residency', models.SmallIntegerField(default=0, help_text='Additional months on top of years_of_residency (0–11).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('previous_address', models.TextField(blank=True, help_text='NULL if born/raised in the barangay.', null=True)),
                ('born_in_barangay', models.BooleanField(default=False, help_text='TRUE if the resident was born in Brgy. Zapatera and has always lived here.')),
                ('requested_for', models.CharField(default='Self', help_text="Whose residency is being certified — usually 'Self' but may be a minor child.", max_length=150)),
                ('requested_for_relation', models.CharField(blank=True, help_text="e.g. 'Self', 'Child', 'Spouse'.", max_length=80, null=True)),
                ('for_enrollment', models.BooleanField(default=False)),
                ('for_employment', models.BooleanField(default=False)),
                ('for_voter_reg', models.BooleanField(default=False)),
                ('for_bank', models.BooleanField(default=False)),
                ('for_utility', models.BooleanField(default=False)),
                ('for_other', models.BooleanField(default=False)),
                ('other_purpose_details', models.TextField(blank=True, help_text='Required when for_other = TRUE.', null=True)),
                ('requesting_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='residency_detail', to='api.certificaterequest')),
            ],
            options={
                'db_table': 'residency_details',
                'indexes': [models.Index(fields=['request'], name='idx_residency_request_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('for_other', False), ('other_purpose_details__isnull', False), _connector='OR'), name='chk_residency_other_purpose'), models.CheckConstraint(condition=models.Q(('for_enrollment', True), ('for_employment', True), ('for_voter_reg', True), ('for_bank', True), ('for_utility', True), ('for_other', True), _connector='OR'), name='chk_residency_at_least_one_purpose')],
            },
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['status'], name='idx_requests_status'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['resident'], name='idx_requests_resident_id'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['cert_type'], name='idx_requests_cert_type'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['-submitted_at'], name='idx_requests_submitted_at'),
        ),
        migrations.AddIndex(
            model_name='statuslog',
            index=models.Index(fields=['request', '-changed_at'], name='idx_status_logs_request_id'),
        ),
    ]
