# Generated by Django 5.2.14 on 2026-05-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False, 'ordering': ['pickup_date']},
        ),
        migrations.AlterModelOptions(
            name='certificaterequest',
            options={'managed': False, 'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='clearancedetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='generatedcertificate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='indigencydetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='residencydetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False, 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterModelOptions(
            name='statuslog',
            options={'managed': False, 'ordering': ['-changed_at']},
        ),
    ]
